---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Configure hostname
      hostname:
        name: centos.wordpress.local
    
    - name: Install EPEL-Release
      dnf:
        name: epel-release
        state: present
        update_cache: yes
    
    - name: Install Dependecies
      dnf:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-pip
          - git
          - wget
          - vim
          - unzip
          - net-tools
          - httpd
          - httpd-tools
          - php 
          - php-json
          - php-curl 
          - php-pear
          - php-mbstring
          - php-pdo
          - php-gd
          - php-mysqlnd
          - php-IDNA_Convert
          - php-enchant
          - enchant 
          - hunspell
    
    - name: Configure PHP-FPM
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        line: "{{ item }}"
      with_items:
        - php_value[max_execution_time]=600
        - php_value[memory_limit]=512M
        - php_value[post_max_size]=256M
        - php_value[upload_max_filesize]=2M
        - php_value[max_input_time]=600
        - php_value[max_input_vars]=2000
        - php_value[date.timezone]=America/Sao_Paulo
    
    - name: Reload PHP-FPM
      service:
        name: php-fpm
        state: reloaded
    
    - name: Get Wordpress latest
      shell: |
        curl -O https://wordpress.org/latest.tar.gz \
        && tar zxvf latest.tar.gz -C /var/www/ \
        && chown -R apache. /var/www/wordpress
    
    - name: Adding wordress config file
      copy:
        src: wordpress.conf
        dest: /etc/httpd/conf.d/
        mode: 0644

    - name: Update httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        search_string: 'DirectoryIndex index.html'
        line: 'DirectoryIndex index.html index.php'
    
    - name: Initialize Httpd
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Update timezone
      shell: timedatectl set-timezone America/Sao_Paulo